version: '3.7'
services:

  mssql:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  proximity-backend:
    ports:
      - "8080:8080"

  proximity-frontend:
    ports:
      - "80:80"
